# Set theme
remote_theme: chesterhow/tale@master

# Site settings
logo: "https://github.com/pj4316/pj4316.github.io/blob/main/_assets/maxlee.jpeg?raw=true"

title: Maxlee blog
description: 'This is Maxlee blog'
url: 'https://pj4316.github.io'
baseurl: ''

author:
  name: 'Max Lee'
  email: pj4316@naver.com
  github_username:  pj4316
  linkedin_username:  https://www.linkedin.com/in/maxlee90

# Collection settings
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

permalink:      /:year-:month-:day/:title
paginate:       5

exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# giscus setting
comments: 
  active: giscus
  giscus:
    repo: pj4316/pj4316.github.io
    repo_id: R_kgDONiz2Dg
    category: Q&A
    category_id: DIC_kwDONiz2Ds4CllmD
