# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://pj4316.github.io'
baseurl: ''
title: 'Maxlee blog'
description: 'This is Maxlee blog'

permalink: pretty
logo: "https://github.com/pj4316/pj4316.github.io/blob/main/_assets/maxlee.jpeg?raw=true"
paginate: 10
toc: true
paginate_path: blog/page:num

social:
  name: MaxLee
  email: pj4316@naver.com
  links:
  - https://www.linkedin.com/in/maxlee90

# Header nav
navigation_header:
- title: Home
  url: /blog/
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

comments: 
  active: giscus
  giscus:
    repo: pj4316/pj4316.github.io
    repo_id: R_kgDONiz2Dg
    category: Q&A
    category_id: DIC_kwDONiz2Ds4CllmD
