# Set theme
remote_theme: joshgerdes/jekyll-uno@master

# Site settings
logo: "https://github.com/pj4316/pj4316.github.io/blob/main/_assets/maxlee.jpeg?raw=true"

title: Maxlee blog
description: 'This is Maxlee blog'
url: 'https://pj4316.github.io'
baseurl: ''

author:
  name: 'Max Lee'
  email: pj4316@naver.com
  github_username:  pj4316
  linkedin_username:  https://www.linkedin.com/in/maxlee90

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
sass:
    sass_dir: _sass
    style: compressed
kramdown:
  input: GFM
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

# giscus setting
comments: 
  active: giscus
  giscus:
    repo: pj4316/pj4316.github.io
    repo_id: R_kgDONiz2Dg
    category: Q&A
    category_id: DIC_kwDONiz2Ds4CllmD
